# Generated by Django 6.0.1 on 2026-02-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_alter_publication_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='slug',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
